id: cap-851dbc
name: Configure the capabilities-store location
Status: Supported
Feature: configurable-component-store-location
Subject:
- store
- node
Planning doc: 2026-08-26-generalize-the-store-declaration-to-taxonomy-and-capabilities
