id: cap-8b206f
name: Declare the work store's home repository
Status: Missing
Planning doc: 2026-08-26-declare-and-provision-the-work-store-s-home-repository
Feature: provisioned-component-stores
Subject:
- store
- store/home-repository
- node
