slug: 2026-09-24-update-the-web-app-s-npm-dependencies-to-clear-the-open-dependabot-alerts
title: Update the web app's npm dependencies to clear the open Dependabot alerts
created: '2026-09-24'
resolution: null
tags:
- web
- tech-debt
owner: brocef@users.noreply.github.com
started: '2026-09-25T03:29:26.159948Z'
